onlyBuiltDependencies:
  - '@getgauge/cli'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma

overrides:
  vue-library: link:../VueLibrary
