minimumReleaseAge: 0
allowBuilds:
    "@endeavour/vue-library": true,
    "@getgauge/cli": true,
    "@parcel/watcher": true,
    "@prisma/client": true,
    "@prisma/engines": true,
    "@tailwindcss/oxide": true,
    "esbuild": true,
    "prisma": true
