sonar.organization=endeavourhealth-discovery
sonar.projectKey=IMQueryRunner
sonar.projectName=IMQueryRunner
sonar.host.url=https://sonarcloud.io
sonar.exclusions=node_modules/**, .nuxt/**, .output/**, dist/**, tests/**, docs/**
sonar.javascript.environments=nodejs, browser
